### ISSUE TITLE
jupyter hub login issue

### ISSUE THREAD

**Issue by rjs360** [Lblackhurst29/ethoscopy#2]
Hi there,
Can you tell me what the login credentials are for the jupyter hub docker?  I believe I have successfully installed the ethoscope-lab/ethoscopy docker image on my node, but I am stuck at the jupyter hub login page.  I tried "default" login credentials posted online (jovyan/jupyter) and my node login credentials, but they do not work.

thanks for any info on this.
-Ruud

**Comment by rjs360** [comment]
Ok never mind that question, I found the login credentials here: https://hub.docker.com/r/ggilestro/ethoscope-lab

But currently it seems it is not working: after login in with said credentials I get this error at http://localhost/hub/spawn-pending/ethoscopelab:

"Spawn failed: Server at http://127.0.0.1:44341/user/ethoscopelab/ didn't respond in 30 seconds"

Does that error look familiar?  I may not have setup the ethoscope-lab docker properly (no experience with docker as of today).

Thanks for any help.
-Ruud

**Comment by ggilestro** [comment]
Did you mount the docker to use an external home folder? If yes, you just need to make sure that the `ethoscopelab` user has `rw` access to that folder.

**Comment by rjs360** [comment]
I followed the instructions here: https://bookstack.lab.gilest.ro/books/ethoscopy/page/getting-started

The only thing I had to add was: ":0.91" after "ggilestro/ethoscope-lab" to access the latest image/container and allow it to be downloaded.  

Should I do more than that, prior to trying to access port 8080 in a browser?  
E.g., I am seeing different instructions at your github (https://github.com/gilestrolab/ethoscopy/tree/main/docker)

I just tried the same installation procedure on another machine running node software (but without any ethoscope wifi connection) at home, and while it seems to install the docker container just fine, I cannot even access localhost:8080 (this may have something to do with network properties from what I can read online), with a "connection was reset" error being thrown.

As an alternative, since I am not looking to necessarily have many users access ethoscopy, would the "basic" installation in a python environment be equally functional as the docker version?

-Ruud

**Comment by ggilestro** [comment]
The second set of instructions on github is there just to explain how the image was created. You can disregard that.
The bookstack instructions are the way to go. 

If you get this error:

> "Spawn failed: Server at http://127.0.0.1:44341/user/ethoscopelab/ didn't respond in 30 seconds"

It means the docker container starts fine but cannot access the home folder of the user you're logging in with. Usually an issue of credentials or perhaps you did not create an ethoscopelab folder in your home?

**Comment by ggilestro** [comment]
Hi @rjs360  - I have updated the instruction set on the [bookstack](https://bookstack.lab.gilest.ro/books/ethoscopy/page/getting-started). Would you be so kind to have a look there and see if now makes sense? I think some important information regarding home folders was given for granted.

**Comment by rjs360** [comment]
Thanks @ggilestro; this is helpful for me, and looks like it may solve my earlier issue with my attempt on my node.  I will give this a try later (today I hope).  One thing that I ran into (as stated above) is that I had to specify the tag for the latest ethoscopy image that had to be installed.  Is that still the case? 

I.e. when I used ".... ggilestro/ethoscope-lab" in the command, I ran into an error stating that it could find the latest image (or something similar). This seemed to be an issue that other dockerhub users (for other softwares) run into sometimes, as there was a solution online (i.e., specify the latest image version tag; in this case adding ":0.91"). This seemed to work (i.e., installation moved forward), other than the "spawn failed" error later... 

I will report back.

**Comment by ggilestro** [comment]
yes, this was also an overlook on my side. I had the image uploaded as `0.91` but not `latest` which is the default tag. Now this is fixed thanks to you.

**Comment by rjs360** [comment]
Ok, apologies for this lengthy comment; I am still having an issue. I am
going to dump the complete output of the various installation commands,
hope that is ok.  I figure it may help diagnose. I ran the following on my
freshly created node:

"sudo pacman -S docker"

This actually threw an error, stating that I should use the -Sy flag to
install a few database file for 'core', 'extra', 'community', 'multilib',
'ethoscope'.  I figured this may be due to the fact that I hadn't run any
ethoscopes on this node, or updated the node software via localhost:8888 (I
am using a secondary node  machine on which I am troubleshooting this
docker issue). So I used the -Sy flag instead.

output:

:: Synchronizing package databases...
 core                  143.6 KiB   116 KiB/s 00:01 [######################]
100%
 extra                1636.8 KiB   667 KiB/s 00:02 [######################]
100%
 community               7.0 MiB  2.02 MiB/s 00:03 [######################]
100%
 multilib              145.5 KiB   713 KiB/s 00:00 [######################]
100%
 ethoscope            1044.0   B  2.14 KiB/s 00:00 [######################]
100%
error: failed retrieving file 'core.db' from manjaro.barata.pt : Could not
resolve host: manjaro.barata.pt
warning: too many errors from manjaro.barata.pt, skipping for the remainder
of this transaction
error: failed retrieving file 'core.db' from mirror.ragenetwork.de : Could
not resolve host: mirror.ragenetwork.de
warning: too many errors from mirror.ragenetwork.de, skipping for the
remainder of this transaction
:: Some packages should be upgraded first...
resolving dependencies...
looking for conflicting packages...

Packages (3) archlinux-keyring-20230504-1  manjaro-keyring-20230615-1
             manjaro-system-20230401-1

Total Download Size:   1.72 MiB
Total Installed Size:  2.34 MiB
Net Upgrade Size:      0.04 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 archlinux-keyrin...  1164.5 KiB   254 KiB/s 00:05 [######################]
100%
 manjaro-keyring-...   563.0 KiB   840 KiB/s 00:01 [######################]
100%
 manjaro-system-2...    29.0 KiB   211 KiB/s 00:00 [######################]
100%
 Total (3/3)          1756.5 KiB   291 KiB/s 00:06 [######################]
100%
(3/3) checking keys in keyring                     [######################]
100%
(3/3) checking package integrity                   [######################]
100%
(3/3) loading package files                        [######################]
100%
(3/3) checking for file conflicts                  [######################]
100%
(3/3) checking available disk space                [######################]
100%
:: Processing package changes...
(1/3) upgrading archlinux-keyring                  [######################]
100%
==> Appending keys from archlinux.gpg...
==> Disabling revoked keys in keyring...
  -> Disabled 2 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  21  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  21  signed:  96  trust: 0-, 0q, 0n, 21m, 0f, 0u
gpg: depth: 2  valid:  73  signed:  27  trust: 73-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-07-07
==> Updating trust database...
gpg: next trustdb check due at 2023-07-07
==> Delete expired Key by Jonas Strassel
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  20  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  20  signed:  96  trust: 0-, 0q, 0n, 20m, 0f, 0u
gpg: depth: 2  valid:  73  signed:  27  trust: 73-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-07-12
(2/3) upgrading manjaro-keyring                    [######################]
100%
==> Appending keys from manjaro.gpg...
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
gpg: error reading key: No public key
==> Locally signing trusted keys in keyring...
  -> Locally signed 3 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 8 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  21  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  21  signed:  96  trust: 0-, 0q, 0n, 21m, 0f, 0u
gpg: depth: 2  valid:  73  signed:  27  trust: 73-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-07-07
(3/3) upgrading manjaro-system                     [######################]
100%
==> Checking for 'os-prober' setup ...
    'os-prober' was already enabled by the user.
==> Checking if graphic drivers need an update ...
:: Running post-transaction hooks...
(1/2) Reloading system manager configuration...
(2/2) Arming ConditionNeedsUpdate...

resolving dependencies...
looking for conflicting packages...

Packages (1) docker-1:24.0.0-1

Total Download Size:    26.90 MiB
Total Installed Size:  107.25 MiB
Net Upgrade Size:       -6.30 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 docker-1:24.0.0-...    26.9 MiB  2.44 MiB/s 00:11 [######################]
100%
error: failed retrieving file 'docker-1:24.0.0-1-x86_64.pkg.tar.zst' from
manjaro.barata.pt : Could not resolve host: manjaro.barata.pt
warning: too many errors from manjaro.barata.pt, skipping for the remainder
of this transaction
error: failed retrieving file 'docker-1:24.0.0-1-x86_64.pkg.tar.zst' from
mirror.ragenetwork.de : Could not resolve host: mirror.ragenetwork.de
warning: too many errors from mirror.ragenetwork.de, skipping for the
remainder of this transaction
(1/1) checking keys in keyring                     [######################]
100%
(1/1) checking package integrity                   [######################]
100%
(1/1) loading package files                        [######################]
100%
(1/1) checking for file conflicts                  [######################]
100%
(1/1) checking available disk space                [######################]
100%
:: Processing package changes...
(1/1) upgrading docker                             [######################]
100%
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
(2/4) Reloading system manager configuration...
(3/4) Reloading device manager configuration...
(4/4) Arming ConditionNeedsUpdate...


After this I ran:

"sudo systemctl enable --now docker"

output:
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service
→ /usr/lib/systemd/system/docker.service.

Then I created the folder "mnt/ethoscopelab" inside of my "home/rs" folder,
and after that finally ran:

"sudo docker run -d -p 8080:8080 \
      --name ethoscope-lab \
      --volume /ethoscope_data/results:/mnt/ethoscope_results:ro \
      --volume /home/rs:/mnt/ethoscopelab \
      --restart=unless-stopped \
      ggilestro/ethoscope-lab"

output:

Unable to find image 'ggilestro/ethoscope-lab:latest' locally
latest: Pulling from ggilestro/ethoscope-lab
6e3729cf69e0: Pull complete
ade329ff1403: Pull complete
db3b5a805d84: Pull complete
208cd0f39b71: Pull complete
2f5b8bde0770: Pull complete
fc7dfbacb6a0: Pull complete
d8af36bc5c2f: Pull complete
a4091873ae51: Pull complete
4f4fb700ef54: Pull complete
dbaa6eb48730: Pull complete
0f93cb5fb545: Pull complete
e531ba29484c: Pull complete
2b94541afb63: Pull complete
603f046b4b69: Pull complete
035b4fb2f684: Pull complete
6014db82c829: Pull complete
c83c39cf81be: Pull complete
bdaaee586218: Pull complete
0bbbede71baf: Pull complete
c4d6e925f196: Pull complete
97f149329ee7: Pull complete
30edd0484956: Pull complete
39242e5c00be: Pull complete
Digest:
sha256:6659ef047fe18a68dc73065890fd2433e0fc0adf73a5315c5bcae82e85c4abaf
Status: Downloaded newer image for ggilestro/ethoscope-lab:latest
04a361d6c07e6d72d1fc367901d63cf1234e9894b7a8005eafe934b35dc8ec8d

I checked if docker is running:

"sudo docker ps"

output:
CONTAINER ID   IMAGE                     COMMAND              CREATED
   STATUS          PORTS
NAMES
04a361d6c07e   ggilestro/ethoscope-lab   "sh -c jupyterhub"   28 minutes
ago   Up 28 minutes   8000/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp
ethoscope-lab

So the docker image/container seems to be running, but when I point Firefox
to "localhost:8080", it tells me that the connection was reset, and no
jupyterlab login page (as before) is loaded...

Any thoughts?

Thanks for the continued support on this.
-Ruud
